name: dz_09_04

on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          echo "Building"
          mkdir build
          touch info.txt
      - name: test
        run: |
          echo "Testing"
          if [ -f info.txt ]; then echo "File info.txt exists"; else echo "File info.txt doesn't exits"; fi
    
  
