name: netologiya 09.04 cicd

on:
  workflow_dispatch
  
jobs:
  runs-on: ubuntu-latest
  build:
    steps:
      - name: build
        run: |
          echo "Building"
          mkdir build
          cd build
          touch info.txt
  tests:
    steps:
      - name: test
        run: |
          echo "Testing"
          if [ -f ./build/info.txt ]; then echo "File info.txt exists"; else echo "File info.txt doesn't exits"; fi